spring:
  h2:
    console:
      enabled: true

# 도커로 띄운 mySQL에 jwtpractice 라는 스키마를 만들어주세요
  datasource:
    url: jdbc:mysql://localhost:3306/jwtpractice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

#  비번 잃어버렸을 경우 메일로 임시 비밀번호를 발급해주기 위한 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: "biznstgic3@gmail.com"
    password: "smhljpwmnuxosjtm"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWw
